#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import semver from "semver";

export function versionSource(version) {
  if (typeof version !== "string" || semver.valid(version) !== version || version.includes("+")) {
    throw new Error(`Invalid npm release version: ${JSON.stringify(version)}`);
  }
  return `// Auto-generated by scripts/generate-version.mjs; do not edit.\nexport const VERSION = ${JSON.stringify(version)};\n`;
}

export function checkVersion(root = process.cwd()) {
  const metadata = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
  const expected = versionSource(metadata.version);
  if (fs.readFileSync(path.join(root, "src/version.ts"), "utf8") !== expected) {
    throw new Error("src/version.ts does not match package.json; run npm run generate-version");
  }
  const lock = JSON.parse(fs.readFileSync(path.join(root, "package-lock.json"), "utf8"));
  if (
    lock.version !== metadata.version ||
    lock.packages?.[""]?.version !== metadata.version ||
    lock.name !== metadata.name ||
    lock.packages?.[""]?.name !== metadata.name
  ) {
    throw new Error("package-lock.json root metadata does not match package.json");
  }
  return metadata;
}

// Imported by release checks; direct invocation generates or checks the tracked source.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.length === 1 && args[0] === "--check") {
    checkVersion();
  } else if (args.length === 0) {
    const { version } = JSON.parse(fs.readFileSync("package.json", "utf8"));
    fs.writeFileSync("src/version.ts", versionSource(version));
  } else {
    throw new Error("Usage: node scripts/generate-version.mjs [--check]");
  }
}
